matrix:
  include:
    - os: linux
      language: python
      python: 3.7
      dist: xenial
      compiler: gcc
      cache:
        directories:
          - $HOME/.conan/data
    - os: osx
      osx_image: xcode11.3
      python: 3.7
      compiler: clang
      cache:
        directories:
          - $HOME/.conan/data
          - /usr/local/Homebrew

before_install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew update; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install conan; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then pip install conan; fi

install:
# Automatic detection of your arch, compiler, etc.
  - conan user
  - conan remote add ghostrobotics "https://api.bintray.com/conan/mathieunassar/ghostrobotics"

script:
  - mkdir build
  - cd build
# Call the build system
  - cmake .. -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTS=ON
  - cmake --build .
# Run the tests
  - ctest . -C Release
